# Generated by Django 6.1 on 2026-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('live', 'Live Events'), ('premiere', 'Premiere'), ('music', 'Music Studio')], default='live', max_length=20),
        ),
    ]
