# Generated by Django 6.1 on 2026-08-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_premiere_remove_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='music/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
