# Generated by Django 6.1 on 2026-08-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_musicstudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='time',
            field=models.CharField(default='Oct. 21, 2024, noon', max_length=100),
        ),
        migrations.AlterField(
            model_name='premiere',
            name='image',
            field=models.ImageField(upload_to='premieres/'),
        ),
    ]
