# Generated by Django 6.1 on 2026-09-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_certification_movie_description_movie_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_video',
            field=models.FileField(blank=True, null=True, upload_to='trailers/'),
        ),
    ]
