# Generated by Django 6.1 on 2026-09-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_trailer_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='time',
            field=models.CharField(default='10:00 AM', max_length=100),
        ),
    ]
