# Generated by Django 6.1 on 2026-09-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_seatreservation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seatreservation',
            name='unique_active_seat_reservation',
        ),
        migrations.RenameField(
            model_name='seatreservation',
            old_name='created_at',
            new_name='reserved_at',
        ),
        migrations.AlterField(
            model_name='seatreservation',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='movies.seat'),
        ),
        migrations.RemoveField(
            model_name='seatreservation',
            name='reservation_token',
        ),
    ]
