# Generated by Django 6.1 on 2026-09-11 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_rename_razorpay_order_id_payment_stripe_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.theater'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seat',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.theater'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='movies.movie'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'booked_at'], name='booking_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['seat', 'booked_at'], name='booking_seat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment'], name='booking_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at', 'theater'], name='booking_date_theater_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at', 'movie'], name='booking_date_movie_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='movie_name_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movie_release_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'updated_at'], name='payment_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['movie', 'created_at'], name='review_movie_date_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_reported'], name='review_reported_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater'], name='seat_theater_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater', 'is_booked'], name='seat_theater_booked_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['seat_number'], name='seat_number_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['expires_at'], name='reservation_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['theater', 'expires_at'], name='reservation_theater_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['movie'], name='theater_movie_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['date'], name='theater_date_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['movie', 'date'], name='theater_movie_date_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['location'], name='theater_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('theater', 'seat_number'), name='unique_theater_seat'),
        ),
    ]
