# Generated by Django 6.1 on 2026-09-11 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_alter_booking_movie_alter_booking_seat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_payment_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_date_theater_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_date_movie_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='seat',
            name='seat_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='theater',
            name='theater_movie_idx',
        ),
        migrations.RenameIndex(
            model_name='seatreservation',
            new_name='reservation_theater_exp_idx',
            old_name='reservation_theater_expiry_idx',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater', 'movie', 'booked_at'], name='booking_theater_movie_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payment_created_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'created_at'], name='review_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['user'], name='reservation_user_idx'),
        ),
    ]
