# Generated by Django 6.1 on 2026-09-11 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_remove_booking_booking_payment_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seat',
            name='unique_theater_seat',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_theater_movie_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movie_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movie_release_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_movie_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_reported_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='seat',
            name='seat_theater_booked_idx',
        ),
        migrations.RemoveIndex(
            model_name='seatreservation',
            name='reservation_theater_exp_idx',
        ),
        migrations.RemoveIndex(
            model_name='seatreservation',
            name='reservation_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='theater',
            name='theater_location_idx',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theater',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment'], name='booking_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater', 'seat_number'], name='seat_theater_number_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['name', 'location'], name='theater_name_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('theater', 'seat_number'), name='unique_seat_per_theater'),
        ),
    ]
