# Generated by Django 6.1 on 2026-09-11 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_remove_seat_unique_theater_seat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='seat',
            name='unique_seat_per_theater',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_seat_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_payment_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_user_date_idx',
        ),
        migrations.AlterField(
            model_name='theater',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment', 'booked_at'], name='booking_payment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payment_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['user', 'theater'], name='reservation_user_theater_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['theater', 'expires_at'], name='reservation_theater_exp_idx'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('theater', 'seat_number'), name='unique_theater_seat'),
        ),
        migrations.AddField(
            model_name='recentlyviewedmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='recentlyviewedmovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recentlyviewedmovie',
            index=models.Index(fields=['user', '-viewed_at'], name='recent_view_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlyviewedmovie',
            index=models.Index(fields=['movie', '-viewed_at'], name='recent_view_movie_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='recentlyviewedmovie',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_recent_movie'),
        ),
    ]
